source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BSForegroundNotification_Example', :exclusive => true do
  pod "BSForegroundNotification", :path => "../"
end

target 'BSForegroundNotification_Tests', :exclusive => true do
  pod "BSForegroundNotification", :path => "../"

end
